server:
  port: ${SERVER_PORT}

spring:
  application:
    name: "Book_Shop"
  jackson:
    time-zone: "Asia/Ho_Chi_Minh"
    date-format: "dd/MM/yyyy HH:mm:ss"
  datasource:
    url: ${DB_URL}
    driver: "com.mysql.cj.jdbc.Driver"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev

jobs:
  cleanup:
    cron: "0 */15 * * * *"
    zone: "Asia/Ho_Chi_Minh"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN}

jwt:
  signerKey: ${JWT_SECRET}
  accessExpMs: ${JWT_EXPIRATION}
  refreshExpMs: ${JWT_REFRESH_EXPIRATION}


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}